### ISSUE TITLE
ToDo's

### ISSUE THREAD

**Issue by FourLineCode** [ItzAkmal/java-chat-engine#1]
- [ ] Change comments
- [ ] Stop server function
- [ ] Stop socket
- [ ] Connect/Disconnect message more obvious
- [ ] Client size resizable
- [ ] Add server broadcast method to send all client
- [ ] Fix command injection issue
- [ ] Maybe replace full clinet ui with JavaFX
